227
KiraCai/premier pull request #10
Opened 2024-07-09 18:56 UTC by KiraCai

search via Debug

2024-07-09 18:56 UTC, KiraCai commented
![image](https://github.com/KiraCai/premier/assets/110127141/baaab39f-fbca-42c0-8fa0-54d48babfff7)

2024-07-09 18:57 UTC, KiraCai commented
в строке 18 можно увидеть здесь

2024-07-10 09:23 UTC, SimukovLeonid requested changes

2024-07-10 09:23 UTC, SimukovLeonid commented on src/main/java/Core/OOP_et_packages/task227.java
> +        if (a > b) {
Попробуй через тернарный написать

2024-08-11 18:40 UTC, KiraCai commented on src/main/java/Core/OOP_et_packages/task227.java
> +        if (a > b) {
сделала

2024-08-12 12:43 UTC, SimukovLeonid approved these changes

2024-11-06 13:32 UTC, merged