228 new branche
KiraCai/premier pull request #11
Opened 2024-07-28 13:32 UTC by KiraCai

228 task

2024-07-29 13:08 UTC, SimukovLeonid requested changes

2024-07-29 13:08 UTC, SimukovLeonid commented on src/main/java/Core/OOP_et_packages/task228.java
> +public class task228 {
Нужно вмержить проверенные ПРы

2024-07-29 13:08 UTC, SimukovLeonid commented on src/main/java/Core/OOP_et_packages/task228.java
> +        while (i < days.length) {
while логичнее использовать, когда есть какое-то условие прерывание. Здесь ты по всему массиву проходишься, будет читабельнее с for-each

2024-07-29 13:08 UTC, SimukovLeonid commented on src/main/java/Core/OOP_et_packages/task228.java
> +                if (days[i] == dayString) {
Строки не так сравнивают

2024-07-29 13:08 UTC, SimukovLeonid commented on src/main/java/Core/OOP_et_packages/task228.java
> +    public static int weekdayCount(String[] days) {
Те же замечания

2024-08-11 18:41 UTC, KiraCai commented on src/main/java/Core/OOP_et_packages/task228.java
> +public class task228 {
вмержила только один, в другом я доделала немного, скажешь что его тоже можно

2024-08-11 18:47 UTC, KiraCai commented on src/main/java/Core/OOP_et_packages/task228.java
> +        while (i < days.length) {
исправила

2024-08-11 18:52 UTC, KiraCai commented on src/main/java/Core/OOP_et_packages/task228.java
> +                if (days[i] == dayString) {
исправила

2024-08-11 18:52 UTC, KiraCai commented on src/main/java/Core/OOP_et_packages/task228.java
> +    public static int weekdayCount(String[] days) {
исправила

2024-08-12 12:39 UTC, SimukovLeonid requested changes

2024-08-12 12:39 UTC, SimukovLeonid commented on src/main/java/Core/OOP_et_packages/task228.java
> +        for(String i : days){
Для переменной вместо имени i лучше использовать название сосмыслом

2024-08-12 12:39 UTC, SimukovLeonid commented on src/main/java/Core/OOP_et_packages/task228.java
> +            for (task217.Day dayEnum : task217.Day.values()) {
Вместо dayEnum я бы использовал dayName

2024-08-12 12:39 UTC, SimukovLeonid commented on src/main/java/Core/OOP_et_packages/task228.java
> +                var dayString = dayEnum.toString();
Нет необходимости объявлять лишнюю переменную т.к можно на следующей строчке использовать внутри equals dayEnum.toString()

2024-11-07 12:31 UTC, KiraCai commented on src/main/java/Core/OOP_et_packages/task228.java
> +        for(String i : days){
исправила

2024-11-07 12:33 UTC, KiraCai commented on src/main/java/Core/OOP_et_packages/task228.java
> +            for (task217.Day dayEnum : task217.Day.values()) {
исправила

2024-11-07 18:09 UTC, SimukovLeonid requested changes

2024-11-07 18:09 UTC, SimukovLeonid commented on src/main/java/Core/OOP_et_packages/task228.java
> +                    if (dayName.isWeekend()) { //считать когда выходной
Здесь и далее убрать комменты, не нужны

2024-11-07 19:20 UTC, KiraCai commented on src/main/java/Core/OOP_et_packages/task228.java
> +                    if (dayName.isWeekend()) { //считать когда выходной
исправила

2024-11-08 18:51 UTC, SimukovLeonid approved these changes

2024-11-09 13:08 UTC, merged