task2311
KiraCai/premier pull request #12
Opened 2024-11-07 13:31 UTC by KiraCai

Use different access modifiers

2024-11-07 18:03 UTC, SimukovLeonid requested changes

2024-11-07 18:03 UTC, SimukovLeonid commented on src/main/java/Core/OOP_et_packages/task231/Human.java
> +    private String getGossip(){
Почему private

2024-11-07 19:23 UTC, KiraCai commented on src/main/java/Core/OOP_et_packages/task231/Human.java
> +    private String getGossip(){
исправила, странно, я не хотела его ставить

2024-11-08 18:50 UTC, SimukovLeonid approved these changes

2024-11-09 13:07 UTC, merged