2.1.7
KiraCai/premier pull request #6
Opened 2024-01-27 23:44 UTC by KiraCai

ляя

2024-03-06 23:01 UTC, KiraCai commented on src/main/java/Core/task216.java
> +    static Cat mia = new Cat();
`    public static void main(String[] args) {
        Cat mia = new Cat();
        Dog lia = new Dog();
        System.out.println(lia.catchCat(mia));
    }`
создала объекты внутри программы

2024-03-06 23:03 UTC, KiraCai commented on src/main/java/Core/task216.java
> +        public static String catchCat(String animals){
`public static String catchCat(Cat animals)`
метод принимает кошку

2024-03-06 23:04 UTC, KiraCai commented on src/main/java/Core/task216.java
> +        //static String sfinx;
удалила ненужные строки

2024-03-06 23:05 UTC, KiraCai commented on src/main/java/Core/task216.java
> +    public static void main(String[] args){
добавила пустые строки

2024-03-06 23:06 UTC, KiraCai commented on src/main/java/Core/task217.java
> +
тут я добавила внутрь всё

2024-03-09 03:20 UTC, SimukovLeonid requested changes

2024-03-11 00:32 UTC, KiraCai commented on src/main/java/Core/Leonid11.java
> +    public static int[] ArraySum(int[] a, int b){
исправила

2024-03-11 00:33 UTC, KiraCai commented on src/main/java/Core/task216.java
> +        static Cat mia = new Cat();
было исправлено

2024-03-11 00:33 UTC, KiraCai commented on src/main/java/Core/task216.java
> +        public static String catchCat(Object animals) {
![image](https://github.com/KiraCai/premier/assets/110127141/779db610-ec3e-4197-beb2-cc3e8edef4eb)
принял кошку

2024-03-13 21:23 UTC, KiraCai commented on src/main/java/Core/task216.java
> +        public static String sayHello(){
исправила

2024-03-13 21:25 UTC, KiraCai commented on src/main/java/Core/OOP_et_packages/task216.java
> +            System.out.println(Dog.sayHello());
исправила

2024-03-13 21:25 UTC, KiraCai commented on src/main/java/Core/OOP_et_packages/task216.java
> +            return Cat.sayHello();
изменила

2024-03-30 01:44 UTC, KiraCai commented on src/main/java/Core/OOP_et_packages/task217.java
> +        public boolean isWeekend(Object da){
сделала но подозрительно

2024-03-30 01:45 UTC, KiraCai commented on src/main/java/Core/OOP_et_packages/task217.java
> +        public String getRusName(Object dayForRu){
сделала без аргументов но странно

2024-03-30 15:36 UTC, SimukovLeonid requested changes

2024-03-30 15:36 UTC, SimukovLeonid commented on src/main/java/Core/OOP_et_packages/task216.java
> +            Dog.sayHello();
Почему метод вызывается на классе?

2024-03-30 15:36 UTC, SimukovLeonid commented on src/main/java/Core/OOP_et_packages/task217.java
> +    public enum Day{
Не то, что нужно, решение есть здесь [линк](https://javarush.com/groups/posts/2260-enum-prakticheskie-primerih-dobavlenie-konstruktorov-i-metodov)

2024-03-30 15:39 UTC, SimukovLeonid requested changes

2024-03-30 15:39 UTC, SimukovLeonid commented on src/main/java/Core/OOP_et_packages/task216.java
> +        public static String sayHello() {
Почему статический

2024-03-30 15:39 UTC, SimukovLeonid commented on src/main/java/Core/OOP_et_packages/task216.java
> +        public static String sayHello() {
Почему статический

2024-03-30 15:39 UTC, SimukovLeonid commented
Нужно исправить конфликты

2024-04-01 17:17 UTC, KiraCai commented on src/main/java/Core/OOP_et_packages/task216.java
> +            Dog.sayHello();
исправила

2024-04-01 17:17 UTC, KiraCai commented on src/main/java/Core/OOP_et_packages/task216.java
> +        public static String sayHello() {
исправила

2024-04-01 17:17 UTC, KiraCai commented on src/main/java/Core/OOP_et_packages/task216.java
> +        public static String sayHello() {
исправила

2024-04-01 19:04 UTC, KiraCai commented on src/main/java/Core/OOP_et_packages/task217.java
> +    public enum Day{
исправила

2024-04-08 20:55 UTC, SimukovLeonid requested changes

2024-04-08 20:55 UTC, SimukovLeonid commented on src/main/java/Core/OOP_et_packages/task216.java
> +        public String catchCat(Cat cat, Dog dog) {
по условию метод принимает только кошку

2024-04-09 21:01 UTC, KiraCai commented on src/main/java/Core/OOP_et_packages/task216.java
> +        public String catchCat(Cat cat, Dog dog) {
исправила на только кошку

2024-04-10 17:08 UTC, SimukovLeonid requested changes

2024-04-10 17:08 UTC, SimukovLeonid commented on src/main/java/Core/OOP_et_packages/task216.java
> +            System.out.println("Гав!");
"У собаки, которая поймала кошку, должен быть вызван метод sayHello()."
Когда у тебя внутри метода объекта вызывается другой метод этого же объекта, его можно вызвать через ключевое слово this или даже просто написав sayHello()

2024-04-11 21:06 UTC, KiraCai commented on src/main/java/Core/OOP_et_packages/task216.java
> +            System.out.println("Гав!");
переделала

2024-05-01 14:47 UTC, merged